name: evently
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^3.0.0
  intl: ^0.15.8
  http: ^0.12.0+2
  shared_preferences: ^0.5.3+1

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/logos/logo.png
    - assets/samples/profile_picture.jpg
    - assets/images/categories/comedy.jpg
    - assets/images/categories/community.jpg
    - assets/images/categories/concert.jpg
    - assets/images/categories/festival.jpg
    - assets/images/categories/fitness.jpg
    - assets/images/categories/food_and_wine.jpg
    - assets/images/categories/nightlife.jpg
    - assets/images/categories/sports.jpg
    - assets/logos/evently.jpg
    - assets/logos/evently-icon.png
    - assets/logos/evently-name.png
    - assets/logos/evently-square-icon.png
    - assets/logos/evently-e.png
    - assets/logos/evently-e-dark.png
    - assets/images/other/picone.jpeg
    - assets/images/other/pictwo.jpeg
    - assets/images/other/picthree.jpeg
    - assets/images/other/picfour.jpeg
    - assets/images/other/picfive.jpeg
    - assets/images/other/picsix.jpeg

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
